const keys=['hijaiyah','iqra','tajwid','doa','surah'];let done=JSON.parse(localStorage.getItem('mengaji_done')||'[]');let best=Number(localStorage.getItem('mengaji_best')||0);let streak=Number(localStorage.getItem('mengaji_streak')||0);
function update(){let p=Math.round(done.length/keys.length*100);document.querySelector('#bar').style.width=p+'%';document.querySelector('#progressTitle').textContent=p+'% selesai';document.querySelector('#ring').textContent=p+'%';document.querySelector('#lessonsDone').textContent=done.length;document.querySelector('#quizScore').textContent=best;document.querySelector('#streak').textContent=streak}
function finish(k){if(!done.includes(k)){done.push(k);localStorage.setItem('mengaji_done',JSON.stringify(done));streak=Math.max(streak,1);localStorage.setItem('mengaji_streak',streak);update();toast('Materi selesai! Semangat melanjutkan 🌙')}else toast('Materi ini sudah selesai ✓')}
function continueLearning(){document.querySelector('#kelas').scrollIntoView();toast(done.length?'Lanjutkan dari materi berikutnya':'Mari mulai dari Huruf Hijaiyah')}
function speak(t){if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='id-ID';speechSynthesis.speak(u)}else toast('Browser belum mendukung suara')}
function toast(t){let x=document.querySelector('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2300)}
const letters=['ا','ب','ت','ث','ج','ح','خ','د','ذ','ر','ز','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ك','ل','م','ن','و','ه','ء','ي'];const lb=document.querySelector('#letters');letters.forEach(x=>{let b=document.createElement('button');b.className='letter';b.textContent=x;b.onclick=()=>speak(x);lb.appendChild(b)});
const qs=[['ب','Ba','Alif','Ta'],['ت','Ta','Ba','Jim'],['م','Mim','Nun','Lam'],['ن','Nun','Mim','Ra'],['ج','Jim','Ha','Kha']];let qi=0,score=0;
function loadQ(){let a=qs[qi],html='';[a[1],a[2],a[3]].sort(()=>Math.random()-.5).forEach(v=>html+=`<button class="answer" onclick="answer('${v}','${a[1]}')">${v}</button>`);document.querySelector('#q').innerHTML=`Huruf <strong>${a[0]}</strong> dibaca...`;document.querySelector('#answers').innerHTML=html;document.querySelector('#feedback').textContent='';document.querySelector('#next').classList.add('hidden')}
function answer(v,c){let f=document.querySelector('#feedback');if(v===c){score++;f.textContent='✅ Benar! MasyaAllah.'}else f.textContent='❌ Belum tepat. Jawaban: '+c;document.querySelectorAll('.answer').forEach(b=>b.disabled=true);document.querySelector('#next').classList.remove('hidden')}
function nextQuestion(){qi++;if(qi>=qs.length){best=Math.max(best,score);localStorage.setItem('mengaji_best',best);update();document.querySelector('#q').innerHTML=`🎉 Kuis selesai! Skor kamu <strong>${score}/${qs.length}</strong>.`;document.querySelector('#answers').innerHTML='';document.querySelector('#next').classList.add('hidden');qi=0;score=0}else loadQ()}
function showSurah(n,no){toast('Materi '+n+' ('+no+') siap dipelajari. Versi berikutnya dapat ditambah audio & ayat lengkap.')}
update();loadQ();